'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

interface Topic {
  id: string
  title: string
  hook: string
  tone: string
  project_id: string
}

interface TopicSelectorProps {
  topics: Topic[]
  projectId: string
  productionMode: string // Pass production mode for script generation prompt
}

export default function TopicSelector({ topics, projectId, productionMode }: TopicSelectorProps) {
  const router = useRouter()
  const supabase = createClient()
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [progress, setProgress] = useState<string | null>(null)

  const toggleTopic = (id: string) => {
    const newSelected = new Set(selectedIds)
    if (newSelected.has(id)) {
      newSelected.delete(id)
    } else {
      newSelected.add(id)
    }
    setSelectedIds(newSelected)
  }

  const toggleAll = () => {
    if (selectedIds.size === topics.length) {
      setSelectedIds(new Set())
    } else {
      setSelectedIds(new Set(topics.map(t => t.id)))
    }
  }

  const saveScriptsToSupabase = async (generatedScripts: any[]) => {
    setProgress('Saving scripts to database...')

    // Map the generated scripts to the database schema
    const scriptsToInsert = generatedScripts.map(script => ({
      project_id: projectId,
      topic_id: script.topic_id, // Assuming the API returns this
      title: script.title,
      script_content: script.script_content, // Assuming the API returns this
      tone: script.tone,
      production_mode: productionMode,
      status: 'draft',
    }))

    const { error: insertError } = await supabase
      .from('scripts')
      .insert(scriptsToInsert)

    if (insertError) {
      console.error('❌ Script Save Error:', insertError)
      setError(`Failed to save scripts: ${insertError.message}.`)
      return false
    }

    return true
  }

  const handleGenerateScripts = async () => {
    if (selectedIds.size === 0) return
    
    setIsGenerating(true)
    setError(null)
    setProgress(`Starting generation for ${selectedIds.size} scripts...`)

    try {
      const topicsToGenerate = topics.filter(t => selectedIds.has(t.id))
      const generatedScripts: any[] = []
      
      // Simulate sequential API calls for demonstration
      for (const [index, topic] of topicsToGenerate.entries()) {
        setProgress(`Generating script for topic ${index + 1} of ${selectedIds.size}: ${topic.title}...`)
        
        // This endpoint will call the AI model to generate content
        const response = await fetch('/api/scripts/generate', { 
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                projectId: projectId,
                topicId: topic.id,
                topicTitle: topic.title,
                topicHook: topic.hook,
                productionMode: productionMode,
                // You would typically include the UserProfile and RegionalData here too
            })
        })

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}))
            throw new Error(`API failed to generate script for "${topic.title}". Server error: ${response.status} ${errorData.message || ''}`)
        }

        const scriptResult = await response.json()
        
        // IMPORTANT: The API should return the generated script content.
        // We'll mock a clean result structure here based on what's needed for the DB save.
        generatedScripts.push({
            topic_id: topic.id,
            title: topic.title,
            script_content: scriptResult.script_content || "Script content placeholder generated by AI.",
            tone: topic.tone,
        })
      }

      // 2. Save all generated scripts to the database
      const success = await saveScriptsToSupabase(generatedScripts)

      if (success) {
        // 3. Navigate the user to the script list page for this project
        router.push(`/dashboard/project/${projectId}/scripts`)
      }

    } catch (err: any) {
      console.error('❌ Script Generation Failed:', err)
      setError(err.message || 'Script generation failed due to a network or server error.')
      setProgress(null)
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className="bg-white shadow rounded-lg p-6">
      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded mb-6 text-sm">
          **Error:** {error}
        </div>
      )}

      {progress && (
        <div className="bg-blue-50 border border-blue-200 text-blue-700 px-4 py-3 rounded mb-6 flex items-center text-sm">
          <svg className="animate-spin h-4 w-4 mr-3" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" /></svg>
          {progress}
        </div>
      )}

      <div className="flex justify-between items-center mb-4">
        <h2 className="text-lg font-medium text-gray-900">Generated Topics</h2>
        <div className="flex gap-2">
             <button 
               onClick={toggleAll}
               disabled={isGenerating}
               className="text-sm text-blue-600 hover:text-blue-800 font-medium disabled:text-gray-400"
             >
               {selectedIds.size === topics.length ? 'Deselect All' : 'Select All'}
             </button>
        </div>
      </div>

      {topics.length > 0 ? (
        <ul className="divide-y divide-gray-200">
          {topics.map((topic) => (
            <li key={topic.id} className="py-4 flex items-start hover:bg-gray-50 transition-colors rounded-md px-2 -mx-2">
              <div className="flex items-center h-5 mt-1">
                <input
                  id={`topic-${topic.id}`}
                  name={`topic-${topic.id}`}
                  type="checkbox"
                  checked={selectedIds.has(topic.id)}
                  onChange={() => toggleTopic(topic.id)}
                  disabled={isGenerating}
                  className="focus:ring-blue-500 h-5 w-5 text-blue-600 border-gray-300 rounded cursor-pointer disabled:opacity-50"
                />
              </div>
              <div className="ml-3 flex-1 cursor-pointer" onClick={() => !isGenerating && toggleTopic(topic.id)}>
                 <label htmlFor={`topic-${topic.id}`} className="font-medium text-gray-900 block cursor-pointer">
                   {topic.title}
                 </label>
                 <p className="text-sm text-gray-500 mt-1">{topic.hook}</p>
                 <div className="mt-2">
                   <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 capitalize">
                     {topic.tone || 'General'}
                   </span>
                 </div>
              </div>
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-gray-500 text-sm">No topics found for this project.</p>
      )}
      
      <div className="mt-6 pt-4 border-t sticky bottom-0 bg-white">
         <button
           onClick={handleGenerateScripts}
           disabled={selectedIds.size === 0 || isGenerating}
           className={`w-full py-3 px-4 rounded-md text-white font-medium transition-colors shadow-sm ${
             selectedIds.size === 0 || isGenerating
               ? 'bg-gray-300 cursor-not-allowed' 
               : 'bg-blue-600 hover:bg-blue-700'
           }`}
         >
           {isGenerating ? progress : `Generate Scripts for ${selectedIds.size} Selected`}
         </button>
      </div>
    </div>
  )
}